// GENERATED by scripts/load — do not edit. Proves scripts/parity/inventory.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/parity/inventory.ts", async () => {
  const mod = await import("../../scripts/parity/inventory.js");
  expect(mod).toBeDefined();
});
