// GENERATED by scripts/load — do not edit. Proves scripts/gen/schema.ts is loadable.
import { test, expect } from "bun:test";
test("loads: scripts/gen/schema.ts", async () => {
  const mod = await import("../../scripts/gen/schema.js");
  expect(mod).toBeDefined();
});
