// GENERATED by scripts/load — do not edit. Proves src/events/async-queue.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/events/async-queue.ts", async () => {
  const mod = await import("../../src/events/async-queue.js");
  expect(mod).toBeDefined();
});
