// GENERATED by scripts/load — do not edit. Proves src/services/tab.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/services/tab.ts", async () => {
  const mod = await import("../../src/services/tab.js");
  expect(mod).toBeDefined();
});
