// GENERATED by scripts/load — do not edit. Proves src/reducers/fleet-state.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/reducers/fleet-state.ts", async () => {
  const mod = await import("../../src/reducers/fleet-state.js");
  expect(mod).toBeDefined();
});
