// GENERATED by scripts/load — do not edit. Proves src/client/rpc.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/client/rpc.ts", async () => {
  const mod = await import("../../src/client/rpc.js");
  expect(mod).toBeDefined();
});
