// GENERATED by scripts/load — do not edit. Proves src/transport/line-splitter.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/transport/line-splitter.ts", async () => {
  const mod = await import("../../src/transport/line-splitter.js");
  expect(mod).toBeDefined();
});
