// GENERATED by scripts/load — do not edit. Proves src/protocol/error.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/protocol/error.ts", async () => {
  const mod = await import("../../src/protocol/error.js");
  expect(mod).toBeDefined();
});
