// GENERATED by scripts/load — do not edit. Proves src/herdr-client.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/herdr-client.ts", async () => {
  const mod = await import("../../src/herdr-client.js");
  expect(mod).toBeDefined();
});
