// GENERATED by scripts/load — do not edit. Proves src/generated/params.ts is loadable.
import { test, expect } from "bun:test";
test("loads: src/generated/params.ts", async () => {
  const mod = await import("../../src/generated/params.js");
  expect(mod).toBeDefined();
});
