import { describe, expect, test } from "bun:test";
import { tsType, objectType, emitDefs, refName } from "../../scripts/gen/ts-type.js";
import { emitParams } from "../../scripts/gen/emit-params.js";
import { emitResults } from "../../scripts/gen/emit-results.js";
import { emitErrors } from "../../scripts/gen/emit-errors.js";
import { emitEvents } from "../../scripts/gen/emit-events.js";
import { header, loadSchema } from "../../scripts/gen/schema.js";
import schema from "../../schema/herdr-api.schema.json";

describe("JSON Schema → TS type expression", () => {
  test("scalars, nullable, arrays, refs, const, enum, unions, intersections", () => {
    expect(tsType({ type: "string" })).toBe("string");
    expect(tsType({ type: ["integer", "null"] })).toBe("number | null");
    expect(tsType({ type: "boolean" })).toBe("boolean");
    expect(tsType({ type: "array", items: { $ref: "#/x/$defs/Foo" } })).toBe("Array<Foo>");
    expect(tsType({ type: "array" })).toBe("Array<unknown>");
    expect(tsType({ const: "ping" })).toBe('"ping"');
    expect(tsType({ enum: ["a", 1] })).toBe('"a" | 1');
    expect(tsType({ oneOf: [{ type: "string" }, { type: "null" }] })).toBe("(string) | (null)");
    expect(tsType({ anyOf: [{ type: "string" }] })).toBe("(string)");
    expect(tsType({ allOf: [{ type: "string" }, { $ref: "#/$defs/B" }] })).toBe("(string) & (B)");
    expect(tsType({})).toBe("unknown"); expect(tsType({ type: "weird" })).toBe("unknown");
    expect(refName("#/schemas/request/$defs/PingParams")).toBe("PingParams");
  });
  test("objects: required vs optional, descriptions, additionalProperties, empty", () => {
    expect(objectType({ properties: { a: { type: "string" }, b: { type: "number", description: "x*/y" } }, required: ["a"] }))
      .toBe('{ "a": string; /** x* /y */ "b"?: number; }');
    expect(objectType({ additionalProperties: { type: "string" } })).toBe("{ [key: string]: string; }");
    expect(objectType({})).toBe("Record<string, never>");
    expect(tsType({ properties: { z: { type: "null" } } })).toBe('{ "z"?: null; }'); // object with no explicit type
  });
  test("emitDefs skips names in the skip set and carries descriptions", () => {
    const out = emitDefs({ A: { type: "string", description: "an A" }, B: { type: "number" } }, new Set(["B"]));
    expect(out).toContain("/** an A */\nexport type A = string;"); expect(out).not.toContain("type B");
  });
});

describe("emitters over the real schema produce what the generator committed", () => {
  const h = header(schema as any);
  test("header names protocol", () => { expect(h).toContain(`protocol ${(schema as any).protocol}`); });
  test("params/results/errors/events emit and match src/generated byte-for-byte", async () => {
    const read = (f: string) => Bun.file(new URL(`../../src/generated/${f}`, import.meta.url)).text();
    expect(emitParams(schema as any, h)).toBe(await read("params.ts"));
    expect(emitResults(schema as any, h)).toBe(await read("results.ts"));
    expect(emitErrors(schema as any, h)).toBe(await read("errors.ts"));
    expect(emitEvents(schema as any, h)).toBe(await read("events.ts"));
  });
  test("loadSchema reads the committed file", async () => { expect((await loadSchema()).protocol).toBe((schema as any).protocol); });
});
